"""empty message

Revision ID: e76741e66076
Revises: 3098589a7c11
Create Date: 2023-08-28 16:12:45.539587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76741e66076'
down_revision = '3098589a7c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthday')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('birthday', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
